import React from 'react';
import { useApp } from '../../context/AppContext';
import { 
  AlertTriangle, 
  ShieldAlert, 
  ArrowRight, 
  Clock, 
  DollarSign, 
  Users, 
  CheckCircle,
  TrendingDown,
  Info
} from 'lucide-react';

export const DecisionSupport: React.FC = () => {
  const { alerts, projects, setActiveTab, setSelectedProjectId } = useApp();

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-xs font-semibold text-slate-500 mb-1">
            <span>Automated Intelligence</span>
            <span>·</span>
            <span className="text-rose-700 font-bold">RFCTLARR Statutory SLA Watchdog</span>
            <span>·</span>
            <span className="text-blue-700 font-medium">Heuristic Risk Engine</span>
          </div>
          <h2 className="text-2xl font-black text-slate-900 tracking-tight">
            Decision Support &amp; Bottleneck Diagnostics
          </h2>
          <p className="text-xs text-slate-500 mt-1 max-w-3xl">
            Proactive scanning of milestone lags, pending sub-registrar mutations, PFMS unreleased DBT tranches, and R&amp;R resettlement occupancy benchmarks.
          </p>
        </div>
      </div>

      {/* Decision Disclaimer Note */}
      <div className="bg-blue-50/70 border border-blue-200 rounded-xl p-3.5 text-xs text-blue-900 flex items-start gap-2.5">
        <Info className="w-4 h-4 text-blue-700 shrink-0 mt-0.5" />
        <div>
          <strong>SIH 2026 Prototype Note:</strong> These decision insights and risk classifications are generated by heuristic rule algorithms for demonstration purposes to assist Central & State administrators in proactively preventing land acquisition project stalling.
        </div>
      </div>

      {/* Critical Alert Cards Grid */}
      <div className="space-y-4">
        {alerts.map((alt) => {
          const isCritical = alt.riskLevel === 'Critical';
          const isHigh = alt.riskLevel === 'High';

          return (
            <div 
              key={alt.id}
              className={`bg-white rounded-xl border p-5 shadow-xs transition-all ${
                isCritical ? 'border-l-4 border-l-rose-600 border-slate-200' :
                isHigh ? 'border-l-4 border-l-amber-500 border-slate-200' :
                'border-l-4 border-l-blue-500 border-slate-200'
              }`}
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-2">
                <div className="flex items-center gap-2 text-xs font-semibold">
                  <span className={`inline-flex items-center gap-1.5 font-bold ${
                    isCritical ? 'text-rose-700' : isHigh ? 'text-amber-700' : 'text-blue-700'
                  }`}>
                    <span className={`w-2 h-2 rounded-full ${isCritical ? 'bg-rose-600' : isHigh ? 'bg-amber-500' : 'bg-blue-600'}`} />
                    {alt.riskLevel} Risk Level
                  </span>
                  <span className="text-slate-400">·</span>
                  <span className="text-slate-600 font-medium">{alt.category}</span>
                  <span className="text-slate-400">·</span>
                  <span className="font-mono text-slate-400 font-normal">Detected {new Date(alt.detectedAt).toLocaleDateString()}</span>
                </div>
                <span className="font-bold text-slate-900 text-xs">{alt.projectName}</span>
              </div>

              <h3 className="text-sm font-bold text-slate-900 mt-1">
                {alt.title}
              </h3>
              <p className="text-xs text-slate-600 mt-1">
                {alt.reason}
              </p>

              {/* Threshold & Metric Badges */}
              <div className="mt-3 pt-3 border-t border-slate-100 flex flex-wrap items-center gap-4 text-xs font-mono">
                <div className="bg-slate-50 px-2.5 py-1 rounded border border-slate-200">
                  <span className="text-slate-500">Current Metric: </span>
                  <strong className="text-rose-700">{alt.metric}</strong>
                </div>
                <div className="bg-slate-50 px-2.5 py-1 rounded border border-slate-200">
                  <span className="text-slate-500">Statutory Limit: </span>
                  <strong className="text-slate-800">{alt.threshold}</strong>
                </div>
              </div>

              {/* Recommended Action Card */}
              <div className="mt-3 bg-slate-50 rounded-lg p-3 border border-slate-200 text-xs flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
                <div>
                  <span className="font-bold text-slate-800">Recommended Executive Action:</span>
                  <p className="text-slate-600 mt-0.5">{alt.recommendedAction}</p>
                </div>
                <button
                  onClick={() => {
                    setSelectedProjectId(alt.projectId);
                    setActiveTab('project_details');
                  }}
                  className="bg-blue-700 hover:bg-blue-800 text-white font-semibold px-3 py-1.5 rounded-lg text-xs flex items-center gap-1 shrink-0 transition-colors"
                >
                  <span>Resolve in Project File</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
